require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 90

RSpec/FilePath:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Encoding:
  EnforcedStyle: always
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  Enabled: true

Style/LambdaCall:
  Enabled: false

Style/SymbolArray:
  Enabled: true

Style/WordArray:
  Enabled: true

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Layout/DotPosition:
  Enabled: true

Layout/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'betagouvbot.gemspec'
    - 'spec/**/*.rb'

RSpec/ExampleLength:
  Max: 7

RSpec/NestedGroups:
  Max: 5
