require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 90

RSpec/FilePath:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DotPosition:
  Enabled: true

Style/Encoding:
  EnforcedStyle: always
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  Enabled: true

Style/LambdaCall:
  Enabled: false

Style/SymbolArray:
  Enabled: true

Style/WordArray:
  Enabled: true

Style/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'betagouvbot.gemspec'
    - 'spec/**/*.rb'

RSpec/MultipleExpectations:
  Max: 4

RSpec/NestedGroups:
  Max: 5
